---
title: "scl-ldn"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
    number_sections: yes
    self_contained: no
editor_options: 
  chunk_output_type: inline
---
<style>
* {  font-family: "Palatino"}
h1{    font-size: 190%}
h2{    font-size: 160%}
h3{    font-size: 150%}
h4{    font-size: 130%}
h5{    font-size: 110%}
h6{    font-size: 90%}
</style>

```{r message=FALSE, warning=FALSE}
library(rgdal)
library(sf)
library(stplanr)
library(tidyr)
library(dplyr)
library(tidyverse)
library(ggraph)
library(ggthemes)
library(mapview)
library(lwgeom)
library(igraph)
library(ggplot2)
library(wesanderson)
library(RColorBrewer)
library(colorRamps)
library(ggspatial)
library(leafgl)
library(leaflet)
library(classInt)
library(ggspatial)
library(gridExtra)
library(cartography)
#install.packages("tidygraph")
library(tidygraph)
#install.packages("ggraph")
library(ggraph)
library(data.table)
install.packages("skimr")
library(skimr)
install.packages("mapedit")
library(mapedit)
```

```{r}
scl <- st_read("/Users/nicolas/Documents/R_GitHub/npalomin.github.io/scl/bandera_full.geojson")
sqscl <- st_read("/Users/nicolas/Documents/R_GitHub/bandera/scl_1sqsq.geojson")
scl_m <- st_read("/Users/nicolas/Documents/R_GitHub/bandera/buffer_diss.geojson")
scl_ml <- st_read("/Users/nicolas/Documents/R_GitHub/bandera/buffer_diss_l.geojson")
scl_mlab <- st_read("/Users/nicolas/Documents/R_GitHub/bandera/scl_m_label.geojson")
```

```{r}
skim(scl) %>%
  as.tibble()
```

```{r fig.height=3, fig.width=3}
h_scl <- scl %>%
  mutate(type = str_extract(NOM_CALLE, '[A-Za-z]+')) %>%
  filter(type != "PASAJE") %>%
  filter(stW >= 6) %>%
  ggplot(aes(stW)) +
  geom_histogram(binwidth = 1)
h_scl
```

```{r}
scl1 <- scl %>%
  mutate(type = str_extract(NOM_CALLE, '[A-Za-z]+')) %>%
  filter(type != "PASAJE"| is.na(type)) %>%
  filter(stL >= 20) %>%
  rename(toW = stW)
```

```{r}
scl_in <- st_intersection(scl1, sqscl)
```

```{r}
df_med <- scl_in %>%
  st_drop_geometry() %>%
  group_by(type) %>%
  summarise(meanC = mean(caW),
            meanT = mean(toW)) %>%
  mutate(type = if_else(is.na(type), "notype", type)) %>%
  as.data.frame()
  
df_med
```

c
```{r}
scl_in1 <- scl_in1 %>%
  mutate(type = if_else(is.na(type), "notype", type)) %>%
  left_join(df_med, by = "type")
```


```{r}
# replace lower values with Mean values
scl_in2 <- scl_in1 %>%
  mutate(toW1 = case_when(toW < 5 ~ meanT,
                          TRUE ~ toW),
         caW1 = case_when(caW < 5 ~ meanC,
                          TRUE ~ caW),
         foW = toW1 - caW1) %>%
  filter(toW1 >= 5)
```

```{r fig.height=3, fig.width=3}
scl_in2 %>%
  ggplot(aes(toW1)) +
  geom_histogram(binwidth = 1)
```

```{r}
# for (i in df_med$type) {
#   scl_in1 <- scl_in %>%
#     mutate(toW = case_when(toW < 5 & type == df_med[i,1] ~ df_med[i,3],
#                            TRUE ~ toW))
# }
```

```{r}
scl_in2 <- scl_in2 %>%
  mutate(pSpace = ntile(foW,3),
         vSpace = ntile(caW1,3),
         vGrade = case_when(vSpace == 1 ~ "A",
                            vSpace == 2 ~ "B",
                            vSpace == 3 ~ "C"),
         classQ = paste(vGrade, pSpace, sep = "")) %>%
  mutate(wsizeQ = case_when(classQ == "A1" ~ 1,
                           classQ == "A2" | classQ == "B1" ~ 2,
                           classQ == "A3" | classQ == "B2" | classQ == "C1" ~ 3,
                           classQ == "C2" | classQ == "B3" ~ 4,
                           classQ == "C3" ~ 5))
```

```{r}
# Function for plotting colors side-by-side
pal <- function(col, border = "light gray", ...){
  n <- length(col)
  plot(0, 0, type="n", xlim = c(0, 1), ylim = c(0, 1),
       axes = FALSE, xlab = "", ylab = "", ...)
  rect(0:(n-1)/n, 0, 1:n/n, 1, col = col, border = border)
}
```

```{r fig.height=2, fig.width=6}
#bipal9 <- brewer.seqseq1
bipal9ch <- c("#e8e6f2", "#b5d3e7", "#4fadd0", "#e5b4d9", "#b8b3d8", "#3983bb", "#de4fa6", "#b03598", "#2a1a8a")
```

```{r fig.height=2, fig.width=7}
pal(bipal9ch)
```

```{r}
scl_mlab <- scl_mlab %>%
  mutate(name= as.character(name))%>%
  mutate(name = na_if(name, "")) # turn empty to NA

scl_mlab
```

```{r fig.height=7, fig.width=5}
scl_in2 %>% 
  mutate(classQ = fct_relevel(classQ, c("A1","A2","A3","B1","B2","B3","C1","C2","C3"))) %>%
  ggplot() +
  geom_sf(aes(col = classQ, size = wsizeQ), show.legend = F, linejoin="mitre") +
  geom_sf(data = scl_ml, size=0.3, linetype="dotted", color="#9E6F4F") + 
  geom_sf_label(data = scl_mlab, aes(label=name), size=2.5, fontface = "italic", family="serif",
                label.size = 0.001, fill=alpha("white",0.7)) +
  geom_sf(data = scl_mlab, size=1, shape=3, color ="#9E6F4F") +
  scale_colour_manual(values = bipal9ch) +
  scale_size_continuous(range = c(0.6,0.9)) +
  annotate(geom = "text", x = -70.6505, y =-33.4393 , label = "Paseo Huerfanos", size = 3, family ="serif", angle = 6.5) +
  annotate(geom = "text", x = -70.6433, y =-33.44 , label = "Cerro\nSanta\nLucia", size = 3, family ="serif") +
  theme_tufte() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0.5, -0.5, 0.5, -0.5, "cm")) +
  annotation_scale(location = "br", style = "ticks", tick_height = 1, height = unit(0, "mm"), line_width = 0.5, pad_x = unit(7, "mm"), text_cex = 0.6)
```


```{r}
ggplot(scl_in2) +
  geom_sf() +
  coord_sf(datum = 5362)
```

```{r}
mapview(scl_in) 
```

# London
```{r}
ldn <- st_read("/Users/nicolas/Documents/R_GitHub/StSpMe/stype/bridges1.gpkg")
lon_m <- st_read("/Users/nicolas/Documents/R_GitHub/bandera/lon_m.gpkg")
```

```{r}
cp <- st_point(x = c(-9866.3110,6713317.2172)) %>% #c(532100.4157,181845.3766)27700 / #c(-0.097418,51.520088)4326
  st_geometry() %>%
  st_sf(crs = 3857)
```

```{r}
cpb <- st_buffer(cp, dist = 1295) # buffer at 1295 m for a 2.59 km side (1 mile) square
cpbb <- st_bbox(cpb) %>%
  st_as_sfc() %>%
  st_geometry() %>%
  st_sf()

cpbb
```

```{r}
mapview(cpbb) + cp + cpb + lon_m
```

```{r}
st_write(cpbb, dsn = "/Users/nicolas/Documents/R_GitHub/bandera/cpbb.gpkg")
```

```{r}
lon3 <- st_transform(ldn, crs=3857) %>%
  st_intersection(cpbb)
```

```{r}
lon_m1 <- lon_m %>%
  st_intersection(cpbb)
```

```{r}
ggplot(lon3) +
  geom_sf() +
  geom_sf(data=lon_m1)
```

```{r}
lon3 <- lon3 %>%
  mutate(pSpace = ntile(foW,3),
         vSpace = ntile(caW,3),
         vGrade = case_when(vSpace == 1 ~ "A",
                            vSpace == 2 ~ "B",
                            vSpace == 3 ~ "C"),
         classQ = paste(vGrade, pSpace, sep = "")) %>%
  mutate(wsizeQ = case_when(classQ == "A1" ~ 1,
                           classQ == "A2" | classQ == "B1" ~ 2,
                           classQ == "A3" | classQ == "B2" | classQ == "C1" ~ 3,
                           classQ == "C2" | classQ == "B3" ~ 4,
                           classQ == "C3" ~ 5))
```

```{r}
lon3 %>% 
  mutate(classQ = fct_relevel(classQ, c("A1","A2","A3","B1","B2","B3","C1","C2","C3"))) %>%
  ggplot() +
  geom_sf(aes(col = classQ, size = wsizeQ), show.legend = F, linejoin="mitre") +
  #geom_sf(data = scl_ml, size=0.3, linetype="dotted", color="#9E6F4F") + 
  geom_sf_label(data = lon_m1, aes(label=name), size=2.5, fontface = "italic", family="serif",
                label.size = 0.001, fill=alpha("white",0.7)) +
  geom_sf(data = lon_m1, size=1, shape=3, color ="#9E6F4F") +
  scale_colour_manual(values = bipal9ch) +
  scale_size_continuous(range = c(0.6,0.9)) +
  #annotate(geom = "text", x = -70.6505, y =-33.4393 , label = "Paseo Huerfanos", size = 3, family ="serif", angle = 6.5) +
  #annotate(geom = "text", x = -70.6433, y =-33.44 , label = "Cerro\nSanta\nLucia", size = 3, family ="serif") +
  theme_tufte() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.margin = margin(0.5, -0.5, 0.5, -0.5, "cm")) +
  annotation_scale(location = "br", style = "ticks", tick_height = 1, height = unit(0, "mm"), line_width = 0.5, pad_x = unit(7, "mm"), text_cex = 0.6)
```

